# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: p4_device_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='p4_device_config.proto',
  package='p4.tmp',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16p4_device_config.proto\x12\x06p4.tmp\"7\n\x0eP4DeviceConfig\x12\x10\n\x08reassign\x18\x01 \x01(\x08\x12\x13\n\x0b\x64\x65vice_data\x18\x02 \x01(\x0c\x62\x06proto3'
)




_P4DEVICECONFIG = _descriptor.Descriptor(
  name='P4DeviceConfig',
  full_name='p4.tmp.P4DeviceConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reassign', full_name='p4.tmp.P4DeviceConfig.reassign', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_data', full_name='p4.tmp.P4DeviceConfig.device_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['P4DeviceConfig'] = _P4DEVICECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

P4DeviceConfig = _reflection.GeneratedProtocolMessageType('P4DeviceConfig', (_message.Message,), {
  'DESCRIPTOR' : _P4DEVICECONFIG,
  '__module__' : 'p4_device_config_pb2'
  # @@protoc_insertion_point(class_scope:p4.tmp.P4DeviceConfig)
  })
_sym_db.RegisterMessage(P4DeviceConfig)


# @@protoc_insertion_point(module_scope)
